// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"DIdemo/dal"
	"DIdemo/handler"
	"DIdemo/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func BuildInjector(db *gorm.DB) (*Injector, error) {
	projectDal := &dal.ProjectDal{
		DB: db,
	}
	questionDal := &dal.QuestionDal{
		DB: db,
	}
	questionModelDal := &dal.QuestionModelDal{
		DB: db,
	}
	projectService := &service.ProjectService{
		ProjectDal:       projectDal,
		QuestionDal:      questionDal,
		QuestionModelDal: questionModelDal,
	}
	projectHandler := &handler.ProjectHandler{
		ProjectService: projectService,
	}
	injector := &Injector{
		ProjectHandler: projectHandler,
	}
	return injector, nil
}
